[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d646ee620b3000b906dd0eef2d46e946e9898f66"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "f2c6732f9c5c405614f288bf955a84ffea5862bd7d9917c112e356f65d4d5da9"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4756+0/libigc.v1.0.4756.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23badad30b3cac2382ea98a87953902ed874a3dd"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "0a73554c8af19db275f9cb642ee3ed20a6f38a4e0091b25c23395543d808b49c"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4756+0/libigc.v1.0.4756.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d49b0a182afbac6d8009ea92e88b9dbc10f486a"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "3203b4ea5935fd427894a554d73167f78ef8ff86425791768c79f9a953bcfbf4"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4756+0/libigc.v1.0.4756.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e92378b7aea6d3a6e27c19dc1d614cc9e11dfe6"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "aaef803f9f0000e2b281f065bcbfb976a99cfb86bcc999807567607d7c41117f"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4756+0/libigc.v1.0.4756.x86_64-linux-gnu-cxx11.tar.gz"
