[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7efd9f852ac640bd5055a56176f368647c02f2ee"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "d3e3e088a3179ac768c8276aab1a0494013ae9084b03b97311bf082cf8fb3c16"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.6712+0/libigc.v1.0.6712.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbaca0952fccda444b3a88fc5d6a8e3c69df10fa"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "fd1e8701e5f77f311c9aa97048ea8e682e045c1aa6462b95abf7fabdd2059321"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.6712+0/libigc.v1.0.6712.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfd1045f353aacba6cfe3d104d16c6ca999a5bfa"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "11544357fdc06e295b39b193fd6fc812f56e889c65d34bda239c81f8b7e7deb6"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.6712+0/libigc.v1.0.6712.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fb6ad50e1e0feb61c9e52857546eeaa2b50beb9"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "69797a2749f7077af3d1e66bcf02717309568c33dbf9650bdbc0a19074ccb926"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.6712+0/libigc.v1.0.6712.x86_64-linux-gnu-cxx11.tar.gz"
