[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a53dbb80887f393a3e1a9c29aeb92d281758a844"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "cdfc93d94a91b93f68c9f0dfd395df058956f3472e4518a2311e76cda4f43d6c"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7862+0/libigc.v1.0.7862.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "725ec57ab1564974acd0ac46eaa85c025619ea80"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "c8adeb2f68e52f9eafb35d01119ad0b2623606715bbab8dfe832eabf8d230c8b"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7862+0/libigc.v1.0.7862.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3802ca49eb7fa59c778f92ca54343ac5c1a31f5c"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "72978a5ea905a9d4c43859c9c87570850a64cc0b21627e7bb64d13be8ea7506f"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7862+0/libigc.v1.0.7862.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87458b334b851344910a81dcf165df93ee137f82"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "ec52a0a18183aef61f1ba45cd5ba2c37e50af009fff0a65f1e7ae52e591967fb"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7862+0/libigc.v1.0.7862.x86_64-linux-gnu-cxx11.tar.gz"
