[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90174f6eb986fe216dcab84897811ed20c6b8973"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "142377ebfde6e8e0275c1eefcffd25e84c265aa038fc798b26ca82eb150cd7dd"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7423+0/libigc.v1.0.7423.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f15973772889fe46be85d3260e899308ee80e4f2"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "f01458d80b274d99537d0d47686709050c22cc57c41dfb2002839b9b5f92f3ad"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7423+0/libigc.v1.0.7423.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a67e719501393d6d8816eed072206d023be171d"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "60e0e7a39ca63890787a511db5adb428a785df32e472f6c8fe88529a4fa995c4"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7423+0/libigc.v1.0.7423.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d336a9d07e728877e3b5b54e67629a1596e5aa2"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "fdfcd22f58d2a4133c8b289c2a396c63e512aec89540e537e90cb48cd9fa1316"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.7423+0/libigc.v1.0.7423.x86_64-linux-gnu-cxx11.tar.gz"
