[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "false"
git-tree-sha1 = "e86e53ee1875e911c5e5eaa5ead13501fc3af13c"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "db06b7cfafe36e7537abfdde6c5ff99426c3f20f3a757febe4deb8073b940283"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v2.34.4+1/libigc.v2.34.4.x86_64-linux-gnu-cxx11-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "true"
git-tree-sha1 = "09721e44503dadeffe70b3282fe211afa3efcb7a"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "3db11cab00f1fd6fb140dad12e1fa89a740752049323eb2642f2503b07bbe2a2"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v2.34.4+1/libigc.v2.34.4.x86_64-linux-gnu-cxx11-debug+true.tar.gz"
