[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "false"
git-tree-sha1 = "93c1d2fe7b6d7ff8b2aa6a1fcbc46bd5458114e9"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "a30bd60cef31feee93952a8f7aa0a6ba344939867f3c344a73c282ef5d4993c7"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13230+1/libigc.v1.0.13230.x86_64-linux-gnu-cxx03-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "true"
git-tree-sha1 = "f74a0a478590f88d59ffb70ca3f9098063cc160a"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "24e690e25c0292fce0e9f761adae980463ef39fd8e66a98bc473f15e9bdf1768"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13230+1/libigc.v1.0.13230.x86_64-linux-gnu-cxx03-debug+true.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "false"
git-tree-sha1 = "27dbce94f20187368da523f5a3a066d9587ae7e9"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "2ecbb251e0e475dab1cb16ced6440db09492a3b6852949cb19092fa61f00e685"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13230+1/libigc.v1.0.13230.x86_64-linux-gnu-cxx11-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "true"
git-tree-sha1 = "9e9ccea9d6649e02b2d51e0062f31edcef4eb669"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "6c35914ddd4b14bf01ad096b550585879a07cf8dc288ea33da0882a12f20461f"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13230+1/libigc.v1.0.13230.x86_64-linux-gnu-cxx11-debug+true.tar.gz"
