[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b55e1297de2d806fe608ab9b2069792944d7a391"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "5c77659e09cc7e7fcdead6d9145a2293a735b74909b1ac90a86b49c4374499f1"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4560+0/libigc.v1.0.4560.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d7a5480dece895257ba55429bf70c1b694ddb38"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "b68e0d11c0ab5cf0ef15b6379f943507c184d15cd2c9f84b68a1d2bdf6e9f2ed"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4560+0/libigc.v1.0.4560.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "602b4805a67692d837ffd73989d352987ff5de1b"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "9d23b31b2cb68e14aba71fcd99a03bfd66f2214b498a574dc2f5cf43a05e1843"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4560+0/libigc.v1.0.4560.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5df604fc05b93cf23c6516468b18a890ffae99de"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "f482fc991f7f8e0ccc75508c592ccdb70a84a7177d6484b94a96669a8d059c96"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4560+0/libigc.v1.0.4560.x86_64-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ab00453f39c60e1dde5d52e7a488ee2e592cd47"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "5483c4f2e5afa30ec681e4e9ec1837235bee85308cf7d3e8d1564102e4075483"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4560+0/libigc.v1.0.4560.x86_64-linux-musl-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d84bcde4b6f780d4063b772750f94b6223cd38fb"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "b56a9840cd57fb76c34453d6da10ddbfb4a8f38dec985e3d888bce96bb842feb"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4560+0/libigc.v1.0.4560.x86_64-linux-musl-cxx11.tar.gz"
