[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "279ab28f992dc4f924593fcaa988c6c1b32f7f4c"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "65d9b9d38524be6de189af4d77e5c6bdd33e204666f62d60e2d4faa14cc3a465"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.8173+0/libigc.v1.0.8173.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4865eacc5b1337d3a2cc91411a71d7b85ce9a194"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "fd19abe6526f60ff03a32b12c7c442b48446f6385a6e9e44552ee26dc18440df"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.8173+0/libigc.v1.0.8173.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d841041ec5c6900bfa7b0641dc4e1a28cec8911a"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "4ec4f4edfd52845ba97b572a187e22e955075a9bd01f56af6f2807f34ea9f3f8"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.8173+0/libigc.v1.0.8173.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c00b3bf3bd3c14a08e80103380f90f123c3425d"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "5b0eab978cc6b06738a7d7c4b86659ee2d84b3c2a0063708136809dee51daaf0"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.8173+0/libigc.v1.0.8173.x86_64-linux-gnu-cxx11.tar.gz"
