[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f53e37c3c70bd5298865584e7e82e74f65b4399c"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "5d85ffaadc1ed73bb856a6ff91c59ea690f8650ead24000d4236505e7952f29f"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3586+2/libigc.v1.0.3586.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e2ba7c1820f3b94aa0ce0207694f5ff8f0bc613"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "c9d1a64d45fcf7c33bb5e5113acd7d2a08f0e074aaacbf36ab6a0a1d5bfa096c"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3586+2/libigc.v1.0.3586.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef8909e62068f778238a78bc79a1acd0b983a3da"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "24bab24dc25a6790d7b8e1ea3f490309c10dca7fbd23a616098d018d98f63844"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3586+2/libigc.v1.0.3586.x86_64-linux-musl-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f77cc257ba043366cf65ff72147a5d56932faab"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "b0cef5e2ac0bf8d89b7e11ba343e00194fee69b2b591d17a6e6bc560e1658780"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3586+2/libigc.v1.0.3586.x86_64-linux-musl-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74582141ea17e0006bd68dbb391476fcff856676"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "58ceca3803ac88d2f7a9e7132623922315d063f2aafd29695952127a02f28cf5"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3586+2/libigc.v1.0.3586.x86_64-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4788fdd216a87d7fa56a27076a997cbeae7dec7e"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "0b27a9cbe01f40e89d7beeae3546813908a0fb6d23a17b6bc5685c046ec0e3c2"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3586+2/libigc.v1.0.3586.x86_64-linux-gnu-cxx03.tar.gz"
