[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ddee37dbfc29f146a5319b64a9ee375e5596a96"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "f6f40be201b3639cc1369000527654e31c0fd937d7dd1fdab5f727af5937bc6c"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13230+0/libigc.v1.0.13230.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14801c1b02ebcc4e9f067588ef0cd61b1d7a33bb"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "baced362cff02f9cf3faf6f5bc4f260ed8cdea118602c18ecacd639a88910588"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13230+0/libigc.v1.0.13230.x86_64-linux-gnu-cxx11.tar.gz"
