[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76ced4ed1bcbad762c44d0d6cb56ed70286d4d8a"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "ad0a99dbaa1fd6eeb7f4f852a969aa83b509d27ec046bfc1e4d77407bcf733aa"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4062+0/libigc.v1.0.4062.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f00c10ec2c6896b434a7ebd6bc34b7c8467f8f89"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "b7ec5a0b5fe052902dea80f0d6fd52b77d9cd3bfad7df497c936f507726a0a4d"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4062+0/libigc.v1.0.4062.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79af5e1fc380faf25491c0de0803e445cd401b65"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "77dfe72705bba35bdbe7d761e27e55724602450951e7501ad458deb7d85c6e13"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4062+0/libigc.v1.0.4062.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38c22ad1bf081351beac1f99eabae3a257bb75f9"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "d23432eec518857b477cd7f90c8582cc7be29f34bac2d193948d62c837d9bf5e"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4062+0/libigc.v1.0.4062.x86_64-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bca4ca0d93ab132d0a57f0bd8a0cbacf3ceb977a"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "1fe83e506ede3612bd97a0a9db32c33bab35faa11adb96d135e5d6de44d627fd"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4062+0/libigc.v1.0.4062.x86_64-linux-musl-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8167ea8b488c729142fce801ce6cfdc85a38f475"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "1f2ac0c8666b2ffb3f7465d56c51e7e82915a1fa4783f277b30851ab2730da3c"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4062+0/libigc.v1.0.4062.x86_64-linux-musl-cxx11.tar.gz"
