[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fb170fd69af4f9be0f4685431424428081173c7"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "da3298c08c465be52fc014314f7f4c6f13a228acf1b00a6b68196316c171ce05"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.10409+0/libigc.v1.0.10409.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93a6f45bb9fc969d3d1a3ec7a95441a517d37e18"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "cbfd75ee44db5ca3f73c977de8537f9f3e4d0fd7b1c686d4183e6ff599af14f2"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.10409+0/libigc.v1.0.10409.x86_64-linux-gnu-cxx11.tar.gz"
