[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61c43554dca5c0b5218044cff33c4ca91bcfe22e"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "b0bac8a89d370951115994eba14b2740a51e31a617a4ede3102f6d474baab46c"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3899+0/libigc.v1.0.3899.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a706dc79a8493584b1d0968ee21a46597f14c2d"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "1d4b9da2102fa8c12c5de5c2996f780eaa23065818aabccbb3694d8a03530f43"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3899+0/libigc.v1.0.3899.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7816b72be6d0193abfef74bd36ed5e27b95f0fa"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "332cf3e3ab0a517a6c9af6942d5f0cf8ded510eccfb6a15f73bf2a06bd74a88a"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3899+0/libigc.v1.0.3899.x86_64-linux-musl-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e34e3060257b4b7cd704e0f5fc085f54517a44e"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "c7f1fe8ec4cbc94a6fcb67a14969f6ffbdb224553764b9ebd300ce12541b6082"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3899+0/libigc.v1.0.3899.x86_64-linux-musl-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3b2e75ea420d78421e60fa1186b40fa2a2850ea"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "c29bb8274c3ca3b80d3aa38021d52dab4e5c41060803180ee810164a430032b8"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3899+0/libigc.v1.0.3899.x86_64-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f08aa532603267a45bab4bd4ae127819f35991b"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "f14c5d87cb14b86a34f654cfebf2090b7dda5f3294cd153c8707c725e037528f"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.3899+0/libigc.v1.0.3899.x86_64-linux-gnu-cxx03.tar.gz"
