[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "false"
git-tree-sha1 = "c4a27fd98344110bd6846a2c9b503537f18441fe"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "e70955462cb25fba666565626790698c1ce87e4f84a19f31ac426b05fba263ce"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v2.14.1+1/libigc.v2.14.1.x86_64-linux-gnu-cxx03-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "true"
git-tree-sha1 = "10283d88d624dcb7c4a3e98360a7be4b5be061a3"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "ed99fb8b7e6bffbae630bcf51d2a618ea9c8279c601ccb9ae81bd0ef1bc92334"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v2.14.1+1/libigc.v2.14.1.x86_64-linux-gnu-cxx03-debug+true.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "false"
git-tree-sha1 = "445fe785a84589be36301d973779ad1e89428369"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "1765a0d45a58bc81ac40d4c28fe5c940d56f70e365ec3bb97300a5a4ac7a61fa"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v2.14.1+1/libigc.v2.14.1.x86_64-linux-gnu-cxx11-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "true"
git-tree-sha1 = "7b33755535302f3bb1a50dcc7443244d7d36c5bd"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "65b455a1b14d4717a747513dcccca60d379a155a5668695b424bdedd129d17ba"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v2.14.1+1/libigc.v2.14.1.x86_64-linux-gnu-cxx11-debug+true.tar.gz"
