[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9298df4f99803c946373966742081592ecf7ed5"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "2c08b4df30e335efc782ad597648e59cfe6b743649e23609dec93c996d8f419a"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.12504+0/libigc.v1.0.12504.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "660a5651620727187c1c4b2ea05edebfc8b38e31"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "1d5f3b367350dba0e70c944d3e8a433325f9e7a32ee89ab23bdc1f2e7ea6e35e"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.12504+0/libigc.v1.0.12504.x86_64-linux-gnu-cxx11.tar.gz"
