[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "false"
git-tree-sha1 = "7f1c2eb944add21d683480710b612cee92f6e835"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "0fe75d2e213d5c04ba04d0cdbb52773b471b5d1c1a5c0774851fa9cf3f0a1794"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.16510+0/libigc.v1.0.16510.x86_64-linux-gnu-cxx03-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "true"
git-tree-sha1 = "1d054cdef0f1497463ab8c3818292c065813e2c7"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "a107e169cee24b2060a04331c4c6840d0d0c649e21ed23624a0a1dea94e495a1"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.16510+0/libigc.v1.0.16510.x86_64-linux-gnu-cxx03-debug+true.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "false"
git-tree-sha1 = "b0ab8adb12efd11af43a65e7a413ee8c2f3d0031"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "2506b9ef4833fdefe05377d8af4af15fc03f18340412babc6dfc05e9a5234e4e"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.16510+0/libigc.v1.0.16510.x86_64-linux-gnu-cxx11-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "true"
git-tree-sha1 = "3906a45f730cfaa7129ce595a29a4439218a6362"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "2664ac4ded5cb007503eb77c772db72e8fc362f7b26aa91dc9a6396b9ea5d643"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.16510+0/libigc.v1.0.16510.x86_64-linux-gnu-cxx11-debug+true.tar.gz"
