[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c57f44bf89a6b6e5432e9c86caaa5748d0b2e8b9"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "5b4f7992a425846a38fbc218ce36491ca4ff50372a152b28ff0e31580d3fde6a"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.5699+0/libigc.v1.0.5699.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d990637d3d3525d4b7347df82542fef65407b6f"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "9d31b3e9aa29f8e0bf7b6c013e717ea0666622d4b85c2f16d74e1a784f272536"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.5699+0/libigc.v1.0.5699.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57cda1923473261116e83e4262dd3bf52d7bc465"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "b7e0769ca70f3154841156beae9c7c4f17591300815c10ea49b506f3aac6da8e"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.5699+0/libigc.v1.0.5699.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a4ee90e436c4b393409cf35c4a47bf1f9b1ed80"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "2d880b03b9875cc29814d5fc182c9a26efc89d3c35ce5c0dc8003b57853200ec"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.5699+0/libigc.v1.0.5699.x86_64-linux-gnu-cxx11.tar.gz"
