[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08f772c23c77199f7f925d5fe5920583e0a6ca5a"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "01ba989da232053ae7f8cfda7884090e9c7dfb7a93ed21b6db34c999058dc69c"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.11061+0/libigc.v1.0.11061.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "151b5c42fbd9c43fa2643a890be45570c10be99e"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "2aac7bc977352167d094372e373e9bd9e1dea9359f44b02af4036a872e017104"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.11061+0/libigc.v1.0.11061.x86_64-linux-gnu-cxx11.tar.gz"
