[[libigc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2d1ee25c64f44e2fbde5810922bea6919fc63f3"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "80d385e0ab18987526721c84499c6fa4a3ee203fa69f4f72118df301a69ad2bb"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4154+0/libigc.v1.0.4154.i686-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95e3ba4d7c63727e9ffe5fff36e448f0341cf9fb"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "246ed23a7bcc1afe4e5d86056b4f9f35610772843c642dcdf486e7ae2485c114"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4154+0/libigc.v1.0.4154.i686-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d62adeed353c90bb003146427cb69e56fabf00c"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "3670ec93b7c6b6381d6d5e47f672fb0068cf689b5cd0f2a00a1b242b0247f981"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4154+0/libigc.v1.0.4154.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81b5dcd0ce0e18037c7fbf1933df914d2408ae6e"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "e37202cc0b837a8c3e7d9ffdbb5459cc29656dd3f4459d8c398616b7c1551f5d"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4154+0/libigc.v1.0.4154.x86_64-linux-gnu-cxx11.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba7877f0eec6a28a54810c2cb2946e0713bc4cab"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "4f3b2880346797e01ee374804f5e5c08034af606084a54e296a10a3ae7968ecf"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4154+0/libigc.v1.0.4154.x86_64-linux-musl-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8bdc7e2f9256213f082356098e914e40aa7ef48"
libc = "musl"
os = "linux"

    [[libigc.download]]
    sha256 = "1639c8f66b3978f365a1224c94f11007b7cded8f10343d8ff9f6ad628a96b5d9"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.4154+0/libigc.v1.0.4154.x86_64-linux-musl-cxx11.tar.gz"
