[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9123a424d44bd2cd19579684e0ef9806830ec23"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "177a3a00ca3875caa067f1969e27f4981070d57982288aca898bbded5e830cbe"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.11702+0/libigc.v1.0.11702.x86_64-linux-gnu-cxx03.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "713b1d09cefba8448668ba8cccc50dfea7433f0c"
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "c67a3d0bd4f0b8ccd699491b6ed6eba1ff9e31579e8f5383e684c5111b60a4ae"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.11702+0/libigc.v1.0.11702.x86_64-linux-gnu-cxx11.tar.gz"
