[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "false"
git-tree-sha1 = "690a307170ec128f724b970481331afa51743492"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "20f167d3eb14857a4e2e44ee9c441853a08609100b32f292588d15c6689d8c8d"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13822+0/libigc.v1.0.13822.x86_64-linux-gnu-cxx03-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
debug = "true"
git-tree-sha1 = "c7baf4bda9ad9238f98a4d29edc9c7d1d98fa59b"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "cd2d70b7b85074032b6342af5510ee06c999b3bc329560f58575557316ba18f6"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13822+0/libigc.v1.0.13822.x86_64-linux-gnu-cxx03-debug+true.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "false"
git-tree-sha1 = "343d1fa4e2c7f8e5f0a1e2e9dc20f2535fbb85f2"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "ec3de8b492d2a88ea8372b58d3dc315b3226265956332c410c900d3de53ff243"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13822+0/libigc.v1.0.13822.x86_64-linux-gnu-cxx11-debug+false.tar.gz"
[[libigc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "true"
git-tree-sha1 = "97093fce872f179f6a650eec9063c4a2a48d8cd2"
lazy = true
libc = "glibc"
os = "linux"

    [[libigc.download]]
    sha256 = "f0cb89416d43204926cd5895ed17fac862860dc60b31e25dffb28ee4f000dddd"
    url = "https://github.com/JuliaBinaryWrappers/libigc_jll.jl/releases/download/libigc-v1.0.13822+0/libigc.v1.0.13822.x86_64-linux-gnu-cxx11-debug+true.tar.gz"
